spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eazybank
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
#    org:
#      springframework:
#        security:
#          web:
    org.springframework.security.web.FilterChainProxy: DEBUG